name: Deployment Exercise 2
on: push
jobs:
    lint: 
      runs-on: macos-latest
      steps: 
        - name: Get Code
          uses: actions/checkout@v3
        - name: install dependencies
          run: npm ci
        - name: lint
          run: npm run lint
    test: 
      runs-on: macos-latest
      steps: 
        - name: Get Code
          uses: actions/checkout@v3
        - name: install dependencies
          run: npm ci
        - name: test code
          run: npm run test
    deploy:
      runs-on: macos-latest
      steps:
          - name: Get Code
            uses: actions/checkout@v3
          - name: install dependencies
            run: npm ci
          - name: buil code
            run: npm run build
          - name: Deploy Code
            run: echo "Deploying Code..."

