name: Github Exercise
on: 
  issues:
    types: [opened, edited, milestoned]
Jobs: 
    test-lint:
        runs_on: macos-latest
        steps: 
        - name: Get Code
          uses: actions/checkout@v3
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with: 
            node-version: 18
        - name: install dependencies
          run: npm ci
        - name: run lint 
          run: npm run lint
          

